CREATE TABLE [dbo].[Role]
(
	[RoleId]		  INT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
	[Name]			  VARCHAR(150) NOT NULL,
	[Description]	  VARCHAR(150) NOT NULL,
	CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED ([RoleId] ASC) WITH (PAD_INDEX = ON, DATA_COMPRESSION = PAGE)
)
